datadir: /local/gainondefor/work/lip6/data/evaelution
prevdatadir: /local/gainondefor/work/lip6/data/companies
gpudatadir: /local/gainondefor/work/data/evaelution
modeldir: /data/gainondefor/evaelution/
label_dict:
  ind: 20_industry_dict.pkl
ppl_rep: profiles_jobs_ind_title
ppl_rep_sk: profiles_jobs_skills_edu_fr_only
json_file: bp_3jobs_desc_edu_skills_industry_date_company_FR